export enum Resources {
  Dashboard = 'dashboard',
  Team = 'team',
  Transaction = 'transaction',
  Developer = 'developer',
  Customer = 'customer',
  Account = 'account',
  Lien = 'lien',
  Product = 'product',
  Loan = 'loan',
  Ledger = 'ledger',
  Audit = 'audit',
  Configuration = 'configuration',
  Security = 'security',
}
